# TOML file for fpm as described at https://fpm.fortran-lang.org/en/spec/manifest.html
name = "M_hashkeys"
version = "0.1.0"
license = "PD"
author = "John S. Urban"
maintainer = "urbanjost@comcast.net"
copyright = "Copyright 2021 John S. Urban"
description= "a collection of hash algorithms"
categories = ["hash"]
keywords = ["fortran", "hash" ]
homepage = "https://github.com/urbanjost/M_hashkeys.git"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = true

[install]
library = false

[[test]]
name="test_suite"
source-dir="test"
main="test_suite_M_hashkeys.f90"
[test.dependencies]
M_framework          = { git = "https://github.com/urbanjost/M_framework.git" }

[dependencies]
M_io       = { git = "https://github.com/urbanjost/M_io.git"      }
M_strings  = { git = "https://github.com/urbanjost/M_strings.git" }
M_system   = { git = "https://github.com/urbanjost/M_system.git"  }
