M_hashkeys: /home/urbanjs/venus/V600/github/M_hashkeys/src/source/sha256/Archive/bitsy-master/bitsy_good.f90 File Reference
bitsy_good.f90 File Reference
Modules
module bitsy
Module for SHA-256 hashing in fortran.
Functions/Subroutines
character(len=64) function bitsy::sha256 (str)
SHA-256 interface function.
character(len=64) function bitsy::dirty_sha256 (str)
Quick and dirty SHA-256 interface function (no bit-swapping).
character(len=64) function bitsy::sha256b (str, swap)
Calculate the SHA-256 hash of the incomming string.
integer(kind=c_int32_t) function bitsy::swap32 (inp)
Swap the byte order on a 32bit integer.
integer(kind=c_int64_t) function bitsy::swap64 (inp)
Swap the byte order on a 64 bit integer.
integer(kind=c_int64_t) function bitsy::swap64a (inp)
Swap the byte order on a 64bit integer as if each half was a 32bit integer to swap.
integer(kind=c_int32_t) function bitsy::ch (a, b, c)
The 'ch' function in SHA-2.
integer(kind=c_int32_t) function bitsy::maj (a, b, c)
The 'maj' function in SHA-2.
integer(kind=c_int32_t) function bitsy::cs0 (a)
The '\Sigma_0' function in SHA-2.
integer(kind=c_int32_t) function bitsy::cs1 (a)
The '\Sigma_1' function in SHA-2.
integer(kind=c_int32_t) function bitsy::ms0 (a)
The '\sigma_0' function in SHA-2.
integer(kind=c_int32_t) function bitsy::ms1 (a)
The '\sigma_1' function in SHA-2.
subroutine bitsy::consume_chunk (str, length, inp, pos0, break, swap)
Copy 16 32bit words of data from str(pos0) to inp(1:16). The data is padded a requiered by the SHA-256 algorithm.
program demo_sha256
subroutine unit_check (name, test, message)
Function/Subroutine Documentation
demo_sha256()
program demo_sha256
References bitsy::dirty_sha256(), bitsy::sha256(), and unit_check().
unit_check()
subroutine demo_sha256::unit_check (character(len=*), intent(in) name, logical, intent(in) test, character(len=*), intent(in) message)
References bitsy::sha256().