M_hashkeys: /home/urbanjs/venus/V600/github/M_hashkeys/src/M_hashkeys__sha3.f90 File Reference
M_hashkeys__sha3.f90 File Reference
Data Types
type m_hashkeys__sha3::sha3_state
Modules
module m_hashkeys__sha3
Functions/Subroutines
subroutine, public m_hashkeys__sha3::sha3_file (d, fname, hdigest)
character(len=size(d) *2) function, public m_hashkeys__sha3::sha3_hexdigest (d)
subroutine, public m_hashkeys__sha3::sha3_update (state, buffer, d)
subroutine m_hashkeys__sha3::sha3_block (S, buffer, r8)
subroutine, public m_hashkeys__sha3::sha3_digest (state, digest)
integer(kind=int8) function, dimension(d/8), public m_hashkeys__sha3::sha3 (buffer, d)
integer(kind=int8) function, dimension(d/8) m_hashkeys__sha3::sha3_keccak (M, d, c)
integer(kind=int8) function, dimension(d/8) m_hashkeys__sha3::sha3_sponge (M, d, r)
integer(kind=int8) function, dimension(b/8) m_hashkeys__sha3::sha3_keccak_p (S, b, nr)
subroutine m_hashkeys__sha3::sha3_round (state, round_index)
subroutine m_hashkeys__sha3::sha3_theta (A)
subroutine m_hashkeys__sha3::sha3_rho (A)
subroutine m_hashkeys__sha3::sha3_pi (A)
subroutine m_hashkeys__sha3::sha3_khi (A)
integer(kind=int8) function m_hashkeys__sha3::sha3_reverse (b)
integer(kind=int64) function, dimension(5, 5) m_hashkeys__sha3::sha3_string2state (S)
integer(kind=int8) function, dimension(sz) m_hashkeys__sha3::sha3_state2string2 (S, sz)
subroutine, public m_hashkeys__sha3::sha3_auto_test ()
subroutine sha3_test11 ()
subroutine sha3_test21 ()
subroutine sha3_test31 ()
subroutine sha3_test41 ()
subroutine sha3_test51 ()
subroutine sha3_test61 ()
subroutine, public m_hashkeys__sha3::test_suite_m_hashkeys__sha3 ()
subroutine test_sha3 ()
subroutine test_sha3_auto_test ()
subroutine test_sha3_digest ()
subroutine test_sha3_file ()
subroutine test_sha3_hexdigest ()
subroutine test_sha3_update ()
Variables
integer, parameter m_hashkeys__sha3::lane = 8
integer, parameter m_hashkeys__sha3::w = 64
integer, parameter m_hashkeys__sha3::ell = 6
integer(kind=int64), dimension(5, 5) m_hashkeys__sha3::sbuf
integer(kind=int64), dimension(24), save m_hashkeys__sha3::rc_c
Function/Subroutine Documentation
sha3_test11()
subroutine sha3_auto_test::sha3_test11 private
References m_hashkeys__sha3::sha3(), m_hashkeys__sha3::sha3_digest(), m_hashkeys__sha3::sha3_hexdigest(), and m_hashkeys__sha3::sha3_update().
sha3_test21()
subroutine sha3_auto_test::sha3_test21 private
References m_hashkeys__sha3::sha3(), m_hashkeys__sha3::sha3_digest(), m_hashkeys__sha3::sha3_hexdigest(), and m_hashkeys__sha3::sha3_update().
sha3_test31()
subroutine sha3_auto_test::sha3_test31 private
References m_hashkeys__sha3::sha3(), m_hashkeys__sha3::sha3_digest(), m_hashkeys__sha3::sha3_hexdigest(), and m_hashkeys__sha3::sha3_update().
sha3_test41()
subroutine sha3_auto_test::sha3_test41 private
References m_hashkeys__sha3::sha3(), m_hashkeys__sha3::sha3_digest(), m_hashkeys__sha3::sha3_hexdigest(), and m_hashkeys__sha3::sha3_update().
sha3_test51()
subroutine sha3_auto_test::sha3_test51 private
References m_hashkeys__sha3::sha3_file().
sha3_test61()
subroutine sha3_auto_test::sha3_test61 private
References m_hashkeys__sha3::sha3_digest(), m_hashkeys__sha3::sha3_hexdigest(), and m_hashkeys__sha3::sha3_update().
test_sha3()
subroutine test_suite_m_hashkeys__sha3::test_sha3
test_sha3_auto_test()
subroutine test_suite_m_hashkeys__sha3::test_sha3_auto_test private
test_sha3_digest()
subroutine test_suite_m_hashkeys__sha3::test_sha3_digest private
test_sha3_file()
subroutine test_suite_m_hashkeys__sha3::test_sha3_file private
test_sha3_hexdigest()
subroutine test_suite_m_hashkeys__sha3::test_sha3_hexdigest private
test_sha3_update()
subroutine test_suite_m_hashkeys__sha3::test_sha3_update private