M_hashkeys: /home/urbanjs/venus/V600/github/M_hashkeys/src/M_hashkeys.f90 File Reference
M_hashkeys.f90 File Reference
Data Types
interface m_hashkeys::crc32_hash
interface m_hashkeys::djb2_hash
interface m_hashkeys::sdbm_hash
interface m_hashkeys::anything_to_bytes
Modules
module m_hashkeys
Functions/Subroutines
character(len=64) function, public m_hashkeys::sha256 (str)
character(len=64) function, public m_hashkeys::dirty_sha256 (str)
character(len=64) function, private m_hashkeys::sha256b (str, swap)
integer(kind=c_int32_t) function, private m_hashkeys::swap32 (inp)
Swap the byte order on a 32bit integer.
integer(kind=c_int64_t) function, private m_hashkeys::swap64 (inp)
Swap the byte order on a 64 bit integer.
integer(kind=c_int64_t) function, private m_hashkeys::swap64a (inp)
Swap the byte order on a 64bit integer as if each half was a 32bit integer to swap.
integer(kind=c_int32_t) function, private m_hashkeys::ch (a, b, c)
The 'ch' function in SHA-2.
integer(kind=c_int32_t) function, private m_hashkeys::maj (a, b, c)
integer(kind=c_int32_t) function, private m_hashkeys::cs0 (a)
The '\Sigma_0' function in SHA-2.
integer(kind=c_int32_t) function, private m_hashkeys::cs1 (a)
The '\Sigma_1' function in SHA-2.
integer(kind=c_int32_t) function, private m_hashkeys::ms0 (a)
The '\sigma_0' function in SHA-2.
integer(kind=c_int32_t) function, private m_hashkeys::ms1 (a)
The '\sigma_1' function in SHA-2.
subroutine, private m_hashkeys::consume_chunk (str, length, inp, pos0, break, swap)
Copy 16 32bit words of data from str(pos0) to inp(1:16). The data is padded as required by the SHA-256 algorithm.
subroutine, public m_hashkeys::test_suite_sha256 ()
subroutine test_swap32
subroutine test_ishftc
subroutine test_ishft
subroutine pad_message1
subroutine pad_message2
subroutine test_ch
subroutine test_maj
subroutine test_cs0
subroutine test_cs1
subroutine test_ms0
subroutine test_ms1
subroutine test_sha256_1
subroutine test_sha256_5
subroutine test_sha256_6
subroutine test_sha256_11
character(len=:) function, allocatable, public m_hashkeys::luhn_checksum (string)
subroutine m_hashkeys::test_luhn_checksum ()
subroutine checkem (goodbad)
integer(kind=int128) function m_hashkeys::djb2_hash_arr (anything, continue)
integer(kind=int128) function m_hashkeys::djb2_hash_scalar (anything, continue)
integer(int64) function m_hashkeys::crc32_hash_arr (anything, continue)
integer(kind=int64) function m_hashkeys::crc32_hash_scalar (anything, continue)
integer(kind=int128) function m_hashkeys::sdbm_hash_arr (anything, continue)
integer(kind=int128) function m_hashkeys::sdbm_hash_scalar (anything, continue)
integer(kind=int128) function, public m_hashkeys::djb2 (anything)
integer function, public m_hashkeys::b3hs_hash_key_jenkins (key, range)
subroutine b3hs_hash_key_jenkins_mix_
subroutine, public m_hashkeys::test_suite_m_hashkeys
character(len=1) function, dimension(:), allocatable m_hashkeys::anything_to_bytes_arr (anything)
character(len=1) function, dimension(:), allocatable m_hashkeys::anything_to_bytes_scalar (anything)
Variables
integer, parameter, public m_hashkeys::int128 = selected_real_kind(1*precision(1.0_int64))
logical, save m_hashkeys::debug =.false.
integer, parameter m_hashkeys::dp =kind(0.0d0)
Function/Subroutine Documentation
b3hs_hash_key_jenkins_mix_()
subroutine b3hs_hash_key_jenkins::b3hs_hash_key_jenkins_mix_ private
checkem()
subroutine test_luhn_checksum::checkem (logical, intent(in) goodbad)
References m_hashkeys::luhn_checksum(), and unit_check().
pad_message1()
subroutine test_suite_sha256::pad_message1 private
References m_hashkeys::consume_chunk(), and unit_check().
pad_message2()
subroutine test_suite_sha256::pad_message2 private
References m_hashkeys::consume_chunk(), and unit_check().
test_ch()
subroutine test_suite_sha256::test_ch private
References m_hashkeys::maj(), and unit_check().
test_cs0()
subroutine test_suite_sha256::test_cs0 private
References m_hashkeys::cs0(), and unit_check().
test_cs1()
subroutine test_suite_sha256::test_cs1 private
References m_hashkeys::cs1(), and unit_check().
test_ishft()
subroutine test_suite_sha256::test_ishft private
References unit_check().
test_ishftc()
subroutine test_suite_sha256::test_ishftc private
References unit_check().
test_maj()
subroutine test_suite_sha256::test_maj private
References m_hashkeys::maj(), and unit_check().
test_ms0()
subroutine test_suite_sha256::test_ms0 private
References m_hashkeys::ms0(), and unit_check().
test_ms1()
subroutine test_suite_sha256::test_ms1 private
References m_hashkeys::ms1(), and unit_check().
test_sha256_1()
subroutine test_suite_sha256::test_sha256_1 private
References m_hashkeys::sha256(), and unit_check().
test_sha256_11()
subroutine test_suite_sha256::test_sha256_11 private
References m_hashkeys::sha256(), and unit_check().
test_sha256_5()
subroutine test_suite_sha256::test_sha256_5 private
References m_hashkeys::dirty_sha256(), m_hashkeys::sha256(), and unit_check().
test_sha256_6()
subroutine test_suite_sha256::test_sha256_6 private
References m_hashkeys::sha256(), and unit_check().
test_swap32()
subroutine test_suite_sha256::test_swap32
References m_hashkeys::swap32(), and unit_check().