M_hashkeys: m_hashkeys__sha3 Module Reference
m_hashkeys__sha3 Module Reference
Data Types
type sha3_state
Functions/Subroutines
subroutine, public sha3_file (d, fname, hdigest)
character(len=size(d) *2) function, public sha3_hexdigest (d)
subroutine, public sha3_update (state, buffer, d)
subroutine sha3_block (S, buffer, r8)
subroutine, public sha3_digest (state, digest)
integer(kind=int8) function, dimension(d/8), public sha3 (buffer, d)
integer(kind=int8) function, dimension(d/8) sha3_keccak (M, d, c)
integer(kind=int8) function, dimension(d/8) sha3_sponge (M, d, r)
integer(kind=int8) function, dimension(b/8) sha3_keccak_p (S, b, nr)
subroutine sha3_round (state, round_index)
subroutine sha3_theta (A)
subroutine sha3_rho (A)
subroutine sha3_pi (A)
subroutine sha3_khi (A)
integer(kind=int8) function sha3_reverse (b)
integer(kind=int64) function, dimension(5, 5) sha3_string2state (S)
integer(kind=int8) function, dimension(sz) sha3_state2string2 (S, sz)
subroutine, public sha3_auto_test ()
subroutine, public test_suite_m_hashkeys__sha3 ()
Variables
integer, parameter lane = 8
integer, parameter w = 64
integer, parameter ell = 6
integer(kind=int64), dimension(5, 5) sbuf
integer(kind=int64), dimension(24), save rc_c
Function/Subroutine Documentation
sha3()
integer(kind=int8) function, dimension(d/8), public m_hashkeys__sha3::sha3 (integer(kind=int8), dimension(:), intent(in) buffer, integer, intent(in) d)
References sha3_keccak().
sha3_auto_test()
subroutine, public m_hashkeys__sha3::sha3_auto_test
References sha3_test21(), sha3_test31(), sha3_test41(), sha3_test51(), and sha3_test61().
sha3_block()
subroutine m_hashkeys__sha3::sha3_block (integer(kind=int64), dimension(5,5), intent(inout) S, integer(kind=int8), dimension(:), intent(in) buffer, integer, intent(in) r8) private
References ell, lane, sha3_reverse(), and sha3_round().
sha3_digest()
subroutine, public m_hashkeys__sha3::sha3_digest (type(sha3_state), intent(inout) state, integer(kind=int8), dimension(:), intent(out) digest)
References sha3_block(), sha3_reverse(), sha3_state2string2(), and w.
sha3_file()
subroutine, public m_hashkeys__sha3::sha3_file (integer, intent(in) d, character(len=*), intent(in) fname, character(len=*), intent(out), optional hdigest)
References sha3_digest(), sha3_hexdigest(), and sha3_update().
sha3_hexdigest()
character(len=size(d)*2) function, public m_hashkeys__sha3::sha3_hexdigest (integer(kind=int8), dimension(:), intent(in) d)
sha3_keccak()
integer(kind=int8) function, dimension(d/8) m_hashkeys__sha3::sha3_keccak (integer(kind=int8), dimension(:), intent(in) M, integer, intent(in) d, integer, intent(in) c) private
References sha3_sponge(), and w.
sha3_keccak_p()
integer(kind=int8) function, dimension(b/8) m_hashkeys__sha3::sha3_keccak_p (integer(kind=int8), dimension(:), intent(in) S, integer, intent(in) b, integer, intent(in) nr) private
References ell, sha3_round(), sha3_state2string2(), and sha3_string2state().
sha3_khi()
subroutine m_hashkeys__sha3::sha3_khi (integer(kind=int64), dimension(5,5), intent(inout) A) private
References sbuf.
sha3_pi()
subroutine m_hashkeys__sha3::sha3_pi (integer(kind=int64), dimension(5,5), intent(inout) A) private
sha3_reverse()
integer(kind=int8) function m_hashkeys__sha3::sha3_reverse (integer(kind=int8), intent(in) b) private
sha3_rho()
subroutine m_hashkeys__sha3::sha3_rho (integer(kind=int64), dimension(5,5), intent(inout) A) private
sha3_round()
subroutine m_hashkeys__sha3::sha3_round (integer(kind=int64), dimension(5,5), intent(inout) state, integer, intent(in) round_index) private
References rc_c, sha3_khi(), sha3_pi(), sha3_rho(), and sha3_theta().
sha3_sponge()
integer(kind=int8) function, dimension(d/8) m_hashkeys__sha3::sha3_sponge (integer(kind=int8), dimension(:), intent(in) M, integer, intent(in) d, integer, intent(in) r) private
References ell, sha3_keccak_p(), sha3_reverse(), and w.
sha3_state2string2()
integer(kind=int8) function, dimension(sz) m_hashkeys__sha3::sha3_state2string2 (integer(kind=int64), dimension(5,5), intent(in) S, integer, intent(in) sz) private
References lane.
sha3_string2state()
integer(kind=int64) function, dimension(5,5) m_hashkeys__sha3::sha3_string2state (integer(kind=int8), dimension(:), intent(in) S) private
References lane.
sha3_theta()
subroutine m_hashkeys__sha3::sha3_theta (integer(kind=int64), dimension(5,5), intent(inout) A) private
sha3_update()
subroutine, public m_hashkeys__sha3::sha3_update (type(sha3_state), intent(inout) state, integer(kind=int8), dimension(:), intent(in) buffer, integer, intent(in), optional d)
References sha3_block(), and w.
test_suite_m_hashkeys__sha3()
subroutine, public m_hashkeys__sha3::test_suite_m_hashkeys__sha3
References test_sha3(), test_sha3_auto_test(), test_sha3_digest(), test_sha3_file(), test_sha3_hexdigest(), and test_sha3_update().
Variable Documentation
ell
integer, parameter m_hashkeys__sha3::ell = 6 private
lane
integer, parameter m_hashkeys__sha3::lane = 8 private
rc_c
integer(kind=int64), dimension(24), save m_hashkeys__sha3::rc_c private
sbuf
integer(kind=int64), dimension(5,5) m_hashkeys__sha3::sbuf private
w
integer, parameter m_hashkeys__sha3::w = 64 private