M_hashkeys: bitsy Module Reference
bitsy Module Reference
Module for SHA-256 hashing in fortran.
Functions/Subroutines
character(len=64) function sha256 (str)
SHA-256 interface function.
character(len=64) function dirty_sha256 (str)
Quick and dirty SHA-256 interface function (no bit-swapping).
character(len=64) function sha256b (str, swap)
Calculate the SHA-256 hash of the incomming string.
integer(kind=c_int32_t) function swap32 (inp)
Swap the byte order on a 32bit integer.
integer(kind=c_int64_t) function swap64 (inp)
Swap the byte order on a 64 bit integer.
integer(kind=c_int64_t) function swap64a (inp)
Swap the byte order on a 64bit integer as if each half was a 32bit integer to swap.
integer(kind=c_int32_t) function ch (a, b, c)
The 'ch' function in SHA-2.
integer(kind=c_int32_t) function maj (a, b, c)
The 'maj' function in SHA-2.
integer(kind=c_int32_t) function cs0 (a)
The '\Sigma_0' function in SHA-2.
integer(kind=c_int32_t) function cs1 (a)
The '\Sigma_1' function in SHA-2.
integer(kind=c_int32_t) function ms0 (a)
The '\sigma_0' function in SHA-2.
integer(kind=c_int32_t) function ms1 (a)
The '\sigma_1' function in SHA-2.
subroutine consume_chunk (str, length, inp, pos0, break, swap)
Copy 16 32bit words of data from str(pos0) to inp(1:16). The data is padded a requiered by the SHA-256 algorithm.
Detailed Description
Module for SHA-256 hashing in fortran.
Author
Mikael Leetmaa @data 05 Jan 2014
Function/Subroutine Documentation
ch()
integer(kind=c_int32_t) function bitsy::ch (a , b , c)
The 'ch' function in SHA-2.
Parameters
a : (in) The a input integer.
b : (in) The b input integer.
c : (in) The c input integer.
Returns
: ch(a,b,c), see the code.
consume_chunk()
subroutine bitsy::consume_chunk (str , length , inp , pos0 , break , swap)
Copy 16 32bit words of data from str(pos0) to inp(1:16). The data is padded a requiered by the SHA-256 algorithm.
Parameters
str : (in) The message to take a chunk from.
length : (in) The length of the message in 8bit words.
inp : (inout) The work area to copy the data to.
pos0 : (inout) Variable to store the start of the next chunk.
break : (inout) Indicates the position in the work flow. break=0 on entry -> continue to consume a chunk, pad if needed. break=2 on entry -> continue to consume, padding was allready done. break=1 one exit -> the last chunk was consumed.
swap : (in) Flag to indicate if swapping to big-endian input (swap=1) should be used. swap=1 is needed for the routine to pass the standard tests, but decreases speed with a factor 2.
References swap32(), and swap64a().
cs0()
integer(kind=c_int32_t) function bitsy::cs0 (a)
The '\Sigma_0' function in SHA-2.
Parameters
a : (in) The a input integer.
Returns
: cs0(a), see the code.
cs1()
integer(kind=c_int32_t) function bitsy::cs1 (a)
The '\Sigma_1' function in SHA-2.
Parameters
a : (in) The a input integer.
Returns
: cs1(a), see the code.
dirty_sha256()
character(len=64) function bitsy::dirty_sha256 (str)
Quick and dirty SHA-256 interface function (no bit-swapping).
Parameters
str : (in) The message to digest.
Returns
: The SHA-256 digest as a string of length 64.
References sha256b().
maj()
integer(kind=c_int32_t) function bitsy::maj (a , b , c)
The 'maj' function in SHA-2.
Parameters
a : (in) The a input integer.
b : (in) The b input integer.
c : (in) The c input integer.
Returns
: maj(a,b,c), see the code.
ms0()
integer(kind=c_int32_t) function bitsy::ms0 (a)
The '\sigma_0' function in SHA-2.
Parameters
a : (in) The a input integer.
Returns
: ms0(a), see the code.
ms1()
integer(kind=c_int32_t) function bitsy::ms1 (a)
The '\sigma_1' function in SHA-2.
Parameters
a : (in) The a input integer.
Returns
: ms1(a), see the code.
sha256()
character(len=64) function bitsy::sha256 (str)
SHA-256 interface function.
Parameters
str : (in) The message to digest.
Returns
: The SHA-256 digest as a string of length 64.
References sha256b().
sha256b()
character(len=64) function bitsy::sha256b (str , swap)
Calculate the SHA-256 hash of the incomming string.
Parameters
str : (in) The message to take digest.
swap : (in) Flag to indicate if swapping to big-endian input (swap=1) should be used. swap=1 is needed for the routine to pass the standard tests, but decreases speed with a factor 2.
Returns
: The SHA-256 digest as a string of length 64.
References ch(), consume_chunk(), cs0(), cs1(), maj(), ms0(), and ms1().
swap32()
integer(kind=c_int32_t) function bitsy::swap32 (inp)
Swap the byte order on a 32bit integer.
Parameters
inp : (in) The integer to byte swap.
Returns
: The byte swapped integer.
swap64()
integer(kind=c_int64_t) function bitsy::swap64 (inp)
Swap the byte order on a 64 bit integer.
Parameters
inp : (in) The integer to byte swap.
Returns
: The byte swapped integer.
swap64a()
integer(kind=c_int64_t) function bitsy::swap64a (inp)
Swap the byte order on a 64bit integer as if each half was a 32bit integer to swap.
Parameters
inp : (in) The integer to byte swap.
Returns
: The byte swapped integer.