M_hashkeys: /home/urbanjs/venus/V600/github/M_hashkeys/src/source/sha256/Archive/bitsy-master/sha256_A.f90 File Reference
sha256_A.f90 File Reference
Modules
module m_hashkeys
Functions/Subroutines
character(len=64) function, public m_hashkeys::sha256 (str)
character(len=64) function, public m_hashkeys::dirty_sha256 (str)
character(len=64) function, private m_hashkeys::sha256b (str, swap)
integer(kind=c_int32_t) function, private m_hashkeys::swap32 (inp)
Swap the byte order on a 32bit integer.
integer(kind=c_int64_t) function, private m_hashkeys::swap64 (inp)
Swap the byte order on a 64 bit integer.
integer(kind=c_int64_t) function, private m_hashkeys::swap64a (inp)
Swap the byte order on a 64bit integer as if each half was a 32bit integer to swap.
integer(kind=c_int32_t) function, private m_hashkeys::ch (a, b, c)
The 'ch' function in SHA-2.
integer(kind=c_int32_t) function, private m_hashkeys::maj (a, b, c)
integer(kind=c_int32_t) function, private m_hashkeys::cs0 (a)
The '\Sigma_0' function in SHA-2.
integer(kind=c_int32_t) function, private m_hashkeys::cs1 (a)
The '\Sigma_1' function in SHA-2.
integer(kind=c_int32_t) function, private m_hashkeys::ms0 (a)
The '\sigma_0' function in SHA-2.
integer(kind=c_int32_t) function, private m_hashkeys::ms1 (a)
The '\sigma_1' function in SHA-2.
subroutine, private m_hashkeys::consume_chunk (str, length, inp, pos0, break, swap)
Copy 16 32bit words of data from str(pos0) to inp(1:16). The data is padded as required by the SHA-256 algorithm.
program demo_sha256
subroutine unit_check (name, test, message)
Function/Subroutine Documentation
demo_sha256()
program demo_sha256
References m_hashkeys::dirty_sha256(), m_hashkeys::sha256(), and unit_check().
unit_check()
subroutine demo_sha256::unit_check (character(len=*), intent(in) name, logical, intent(in) test, character(len=*), intent(in) message)
References m_hashkeys::sha256().